<?php
// CLI helper: prints a ready-to-run SQL INSERT for a superadmin user
// with a proper bcrypt password hash. Delete after use.
//
// Usage:
//   php gen-superadmin-sql.php <username> <email> <password> [full_name]
//
// Example:
//   php gen-superadmin-sql.php superadmin admin@wakulima.org 'MySecretPass!' 'Super Admin'
//
// Pipe the output straight into MySQL:
//   php gen-superadmin-sql.php superadmin admin@wakulima.org 'MySecretPass!' \
//     | mysql -u DBUSER -p DBNAME

if (PHP_SAPI !== 'cli') { http_response_code(403); exit('CLI only.'); }
if ($argc < 4) {
    fwrite(STDERR, "Usage: php gen-superadmin-sql.php <username> <email> <password> [full_name]\n");
    exit(1);
}
$user  = $argv[1];
$email = $argv[2];
$pass  = $argv[3];
$full  = $argv[4] ?? $user;
$hash  = password_hash($pass, PASSWORD_DEFAULT);

$esc = fn($s) => str_replace("'", "''", $s);

echo "-- Generated by gen-superadmin-sql.php\n";
echo "ALTER TABLE `users`\n";
echo "    MODIFY COLUMN `role` ENUM('superadmin','admin','editor') NOT NULL DEFAULT 'admin';\n\n";
echo "INSERT INTO `users` (`username`, `email`, `password`, `full_name`, `role`) VALUES\n";
echo "    ('" . $esc($user) . "', '" . $esc($email) . "', '" . $esc($hash) . "', '" . $esc($full) . "', 'superadmin')\n";
echo "ON DUPLICATE KEY UPDATE\n";
echo "    `password` = VALUES(`password`),\n";
echo "    `email`    = VALUES(`email`),\n";
echo "    `full_name`= VALUES(`full_name`),\n";
echo "    `role`     = 'superadmin';\n";
